<x-layout>
  <section class="container hero">
    <div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> IDEAS CONNECT. POSSIBILITIES OPEN.</p><h1>Thoughtful<br>software.<br><span class="accent-text">Real-world</span><br>impact<span class="lime-dot">.</span></h1><p class="hero-description">We’re Nexus Qart. We turn business ideas into digital experiences that feel simple, work beautifully, and serve a purpose.</p><div class="button-group"><a class="button button-dark" href="{{ route('products') }}">Explore our work <span aria-hidden="true">↗</span></a><a class="text-link" href="{{ route('services') }}">What we do <span aria-hidden="true">→</span></a></div></div>
    <div class="hero-visual"><x-product-preview /></div>
  </section>
  <div class="container principles-strip"><span>SMALL DETAILS. BIG DIFFERENCE.</span><p>Built around people <b aria-hidden="true">✳</b> Designed for clarity <b aria-hidden="true">✳</b> Made to be useful</p></div>
  <section class="container section intro-grid"><p class="eyebrow">01 / THE NEXUS QART WAY</p><div><h2>Technology should move<br>your business <span class="muted">forward.</span></h2><p class="large-copy">We bring design and engineering together to solve practical problems. From your first website to your next digital product, we start with what matters to you.</p><a class="text-link" href="{{ route('about') }}">Meet Nexus Qart <span aria-hidden="true">↗</span></a></div></section>
  <section class="section services-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">02 / WHAT WE DO</p><h2>Good thinking.<br>Better digital experiences.</h2></div><p>From a first conversation<br>to something people can use.</p></div><x-service-list /></div></section>
  <section class="container section"><div class="section-heading"><div><p class="eyebrow">03 / BUILT BY NEXUS QART</p><h2>Our thinking, in action.</h2></div><a class="text-link" href="{{ route('products') }}">Explore our products ↗</a></div><a class="featured-product" href="{{ route('nexa') }}"><div class="featured-copy"><span class="pill">FEATURED PRODUCT</span><h3>Nexa<span>Less paper.<br>More possibility.</span></h3><p>Digital menus, catalogues and AI assistance — with your content and your branding.</p><span class="text-link">Discover Nexa <span aria-hidden="true">↗</span></span></div><div class="featured-art nexa-featured-art"><img src="{{ asset('assets/nexa-menu.png') }}" width="357" height="792" alt="Nexa customer menu with search, categories and a featured item"><span class="art-caption">NEXA / CUSTOMER MENU</span></div></a></section>
  <x-cta />
</x-layout>
